### ISSUE TITLE
Extension not working in Firefox 80.0

### ISSUE THREAD

**Issue by adam-sroka** [kewisch/send-to-things-extension#2]
Hello,

the send-to-things-extension is not working in a fresh install of Firefox. After clicking on the button, nothing happens, even though Things 3 is running, see below. Any ideas on how to fix this 😊?

**Details:**
Firefox version: 80.0
Things version: 3.12.3
macOS version: 10.15.6

![things_extension_bug](https://user-images.githubusercontent.com/45038919/91742821-2aedee00-ebb7-11ea-8a74-d398f0dda3f3.gif)

**Comment by adam-sroka** [comment]
From the reviews on Firefox Add-ons, it seems to have stopped working in previous versions as well.

![image](https://user-images.githubusercontent.com/45038919/91743250-d1d28a00-ebb7-11ea-8ed1-3c6452022e1c.png)

**Comment by kewisch** [comment]
Hmm strange, no tab opening either in your screencast. It works for me using Things 3.12.6, Firefox Nightly on macOS. Can you go to about:debugging, click inspect, then go to the console and let me know if any errors show up when you click the button?

**Comment by zuchmanski** [comment]
@kewisch FYI I had the same issue. Patch suggested by @el-ee fixed the problem: https://github.com/kewisch/send-to-things-extension/pull/1.

**Comment by kewisch** [comment]
Thank for confirming, I've merged #1 and will spin a new release soon.

**Comment by adam-sroka** [comment]
> Hmm strange, no tab opening either in your screencast. It works for me using Things 3.12.6, Firefox Nightly on macOS. Can you go to about:debugging, click inspect, then go to the console and let me know if any errors show up when you click the button?

Very sorry for not getting back to this — it got buried in todos and I eventually stopped using the extension. I'm glad it got fixed eventually!

**Comment by kewisch** [comment]
No worries at all, it was the same for me!
