### ISSUE TITLE
Can't see the extension icon (on FF 110.0.1)

### ISSUE THREAD

**Issue by halloleo** [kewisch/send-to-things-extension#3]
Just installed Send To things on Firefox 110.0.1. (The extension looks  _just_ like what I wanted!)

I gave it the needed tab permissions, but I could not see the extension icon. 

Then I restarted Firefox, but still I cannot see the extension icon in the toolbar.

Any idea what's going wrong?

**Comment by kewisch** [comment]
Hmm I don't know what is going on there. The icon shows for me. Maybe this was during the upgrade to MV3? Would you mind trying again with the latest Firefox?

**Comment by halloleo** [comment]
@kewisch Sorry to say. I have moved on. I don't use FF much anymore. I now use Vivaldi with Things'  Quick Entry feature.

But thanks for following up!
